query getUserById($id: Int!){
  getUserById (id: $id ) {
    id,
    username,
    firstName,
    lastName,
    correo,
    profiles{
   		foto,
    	fechaNacimiento,
    	genero,
    	descripcion,
    	noTelefono,
    	edad
    }
  }
}
